export const SECTIONDATA = [
  {
    id: "1",
    title: "Popular Vendors",
    vendors: [
      {
        uid: "v1",
        name: "Taco Fiesta",
        price: "$",
        rating: 4.5,
        latitude: 36.7378,
        longitude: -119.7871,
        image: "https://via.placeholder.com/150",
        description: "A lively spot offering the best tacos in town.",
      },
      {
        uid: "v2",
        name: "Burger Haven",
        price: "$$",
        rating: 4.0,
        latitude: 36.7398,
        longitude: -119.7891,
        image: "https://via.placeholder.com/150",
        description: "Classic and gourmet burgers served fresh.",
      },
      {
        uid: "v3",
        name: "Gourmet Grills",
        price: "$$$",
        rating: 3.8,
        latitude: 36.7358,
        longitude: -119.7851,
        image: "https://via.placeholder.com/150",
        description: "Upscale grilled dishes for discerning tastes.",
      },
      {
        uid: "v4",
        name: "Pizza Wagon",
        price: "$",
        rating: 4.7,
        latitude: 36.7388,
        longitude: -119.7861,
        image: "https://via.placeholder.com/150",
        description: "Fresh, cheesy pizzas with various toppings.",
      },
      {
        uid: "v5",
        name: "Sandwich Stop",
        price: "$$",
        rating: 4.2,
        latitude: 36.7368,
        longitude: -119.7881,
        image: "https://via.placeholder.com/150",
        description: "Delicious sandwiches made to order.",
      },
    ],
  },
  {
    id: "2",
    title: "Nearby Vendors",
    vendors: [
      {
        uid: "v6",
        name: "BBQ Express",
        price: "$$",
        rating: 3.9,
        latitude: 36.7408,
        longitude: -119.7901,
        image: "https://via.placeholder.com/150",
        description: "Quick and savory BBQ dishes.",
      },
      {
        uid: "v7",
        name: "Seafood Shack",
        price: "$$$",
        rating: 4.8,
        latitude: 36.7418,
        longitude: -119.7911,
        image: "https://via.placeholder.com/150",
        description: "Fresh seafood served with a smile.",
      },
      {
        uid: "v8",
        name: "Hot Dog Haven",
        price: "$",
        rating: 4.1,
        latitude: 36.7428,
        longitude: -119.7921,
        image: "https://via.placeholder.com/150",
        description: "Hot dogs with a variety of toppings.",
      },
      {
        uid: "v9",
        name: "Vegan Delights",
        price: "$$",
        rating: 4.3,
        latitude: 36.7438,
        longitude: -119.7931,
        image: "https://via.placeholder.com/150",
        description: "Healthy vegan meals for everyone.",
      },
      {
        uid: "v10",
        name: "Dessert Truck",
        price: "$$$",
        rating: 4.0,
        latitude: 36.7448,
        longitude: -119.7941,
        image: "https://via.placeholder.com/150",
        description: "Sweet treats and desserts on the go.",
      },
    ],
  },
  {
    id: "3",
    title: "Mexican",
    vendors: [
      {
        uid: "v1",
        name: "Taco Fiesta",
        price: "$",
        rating: 4.5,
        latitude: 36.7378,
        longitude: -119.7871,
        image: "https://via.placeholder.com/150",
        description: "A lively spot offering the best tacos in town.",
      },
      {
        uid: "v11",
        name: "Burrito Bros",
        price: "$$",
        rating: 4.6,
        latitude: 36.7458,
        longitude: -119.7951,
        image: "https://via.placeholder.com/150",
        description: "Burritos packed with fresh ingredients.",
      },
      {
        uid: "v12",
        name: "Quesadilla Queen",
        price: "$",
        rating: 4.4,
        latitude: 36.7468,
        longitude: -119.7961,
        image: "https://via.placeholder.com/150",
        description: "Cheesy quesadillas with creative fillings.",
      },
      {
        uid: "v13",
        name: "Nacho Nirvana",
        price: "$$",
        rating: 4.7,
        latitude: 36.7478,
        longitude: -119.7971,
        image: "https://via.placeholder.com/150",
        description: "Loaded nachos with all the fixings.",
      },
      {
        uid: "v14",
        name: "Taco Truck",
        price: "$",
        rating: 4.3,
        latitude: 36.7488,
        longitude: -119.7981,
        image: "https://via.placeholder.com/150",
        description: "Authentic tacos served fast and fresh.",
      },
    ],
  },
  {
    id: "4",
    title: "American",
    vendors: [
      {
        uid: "v2",
        name: "Burger Haven",
        price: "$$",
        rating: 4.0,
        latitude: 36.7398,
        longitude: -119.7891,
        image: "https://via.placeholder.com/150",
        description: "Classic and gourmet burgers served fresh.",
      },
      {
        uid: "v3",
        name: "Gourmet Grills",
        price: "$$$",
        rating: 3.8,
        latitude: 36.7358,
        longitude: -119.7851,
        image: "https://via.placeholder.com/150",
        description: "Upscale grilled dishes for discerning tastes.",
      },
      {
        uid: "v4",
        name: "Pizza Wagon",
        price: "$",
        rating: 4.7,
        latitude: 36.7388,
        longitude: -119.7861,
        image: "https://via.placeholder.com/150",
        description: "Fresh, cheesy pizzas with various toppings.",
      },
      {
        uid: "v5",
        name: "Sandwich Stop",
        price: "$$",
        rating: 4.2,
        latitude: 36.7368,
        longitude: -119.7881,
        image: "https://via.placeholder.com/150",
        description: "Delicious sandwiches made to order.",
      },
      {
        uid: "v15",
        name: "Fried Chicken Co.",
        price: "$$",
        rating: 4.5,
        latitude: 36.7498,
        longitude: -119.7991,
        image: "https://via.placeholder.com/150",
        description: "Crispy fried chicken with a southern twist.",
      },
    ],
  },
  {
    id: "5",
    title: "Japanese",
    vendors: [
      {
        uid: "v16",
        name: "Sushi Station",
        price: "$$$",
        rating: 4.8,
        latitude: 36.7508,
        longitude: -119.8001,
        image: "https://via.placeholder.com/150",
        description: "Delicious sushi rolls made fresh daily.",
      },
      {
        uid: "v17",
        name: "Ramen Road",
        price: "$$",
        rating: 4.6,
        latitude: 36.7518,
        longitude: -119.8011,
        image: "https://via.placeholder.com/150",
        description: "Hearty ramen bowls with authentic flavors.",
      },
      {
        uid: "v18",
        name: "Tempura Truck",
        price: "$$",
        rating: 4.4,
        latitude: 36.7528,
        longitude: -119.8021,
        image: "https://via.placeholder.com/150",
        description: "Crispy and golden tempura dishes.",
      },
      {
        uid: "v19",
        name: "Teriyaki Treats",
        price: "$",
        rating: 4.3,
        latitude: 36.7538,
        longitude: -119.8031,
        image: "https://via.placeholder.com/150",
        description: "Savory teriyaki meals that delight.",
      },
      {
        uid: "v20",
        name: "Sashimi Stop",
        price: "$$$",
        rating: 4.7,
        latitude: 36.7548,
        longitude: -119.8041,
        image: "https://via.placeholder.com/150",
        description: "Fresh sashimi platters for seafood lovers.",
      },
    ],
  },
];
