export const SECTIONDATA = [
    {
      id: "1",
      title: "Popular Vendors",
      vendors: [
        {
          uid: "v1",
          name: "Taco Fiesta",
          price: "$",
          rating: 4.5,
          latitude: 36.7378,
          longitude: -119.7871,
          image: "https://via.placeholder.com/150",
        },
        {
          uid: "v2",
          name: "Burger Haven",
          price: "$$",
          rating: 4.0,
          latitude: 36.7398,
          longitude: -119.7891,
          image: "https://via.placeholder.com/150",
        },
        {
          uid: "v3",
          name: "Gourmet Grills",
          price: "$$$",
          rating: 3.8,
          latitude: 36.7358,
          longitude: -119.7851,
          image: "https://via.placeholder.com/150",
        },
        {
          uid: "v4",
          name: "Pizza Wagon",
          price: "$",
          rating: 4.7,
          latitude: 36.7388,
          longitude: -119.7861,
          image: "https://via.placeholder.com/150",
        },
        {
          uid: "v5",
          name: "Sandwich Stop",
          price: "$$",
          rating: 4.2,
          latitude: 36.7368,
          longitude: -119.7881,
          image: "https://via.placeholder.com/150",
        },
      ],
    },
    {
      id: "2",
      title: "Nearby Vendors",
      vendors: [
        {
          uid: "v6",
          name: "BBQ Express",
          price: "$$",
          rating: 3.9,
          latitude: 36.7408,
          longitude: -119.7901,
          image: "https://via.placeholder.com/150",
        },
        {
          uid: "v7",
          name: "Seafood Shack",
          price: "$$$",
          rating: 4.8,
          latitude: 36.7418,
          longitude: -119.7911,
          image: "https://via.placeholder.com/150",
        },
        {
          uid: "v8",
          name: "Hot Dog Haven",
          price: "$",
          rating: 4.1,
          latitude: 36.7428,
          longitude: -119.7921,
          image: "https://via.placeholder.com/150",
        },
        {
          uid: "v9",
          name: "Vegan Delights",
          price: "$$",
          rating: 4.3,
          latitude: 36.7438,
          longitude: -119.7931,
          image: "https://via.placeholder.com/150",
        },
        {
          uid: "v10",
          name: "Dessert Truck",
          price: "$$$",
          rating: 4.0,
          latitude: 36.7448,
          longitude: -119.7941,
          image: "https://via.placeholder.com/150",
        },
      ],
    },
    {
      id: "3",
      title: "Mexican",
      vendors: [
        {
          uid: "v1",
          name: "Taco Fiesta",
          price: "$",
          rating: 4.5,
          latitude: 36.7378,
          longitude: -119.7871,
          image: "https://via.placeholder.com/150",
        },
        {
          uid: "v11",
          name: "Burrito Bros",
          price: "$$",
          rating: 4.6,
          latitude: 36.7458,
          longitude: -119.7951,
          image: "https://via.placeholder.com/150",
        },
        {
          uid: "v12",
          name: "Quesadilla Queen",
          price: "$",
          rating: 4.4,
          latitude: 36.7468,
          longitude: -119.7961,
          image: "https://via.placeholder.com/150",
        },
        {
          uid: "v13",
          name: "Nacho Nirvana",
          price: "$$",
          rating: 4.7,
          latitude: 36.7478,
          longitude: -119.7971,
          image: "https://via.placeholder.com/150",
        },
        {
          uid: "v14",
          name: "Taco Truck",
          price: "$",
          rating: 4.3,
          latitude: 36.7488,
          longitude: -119.7981,
          image: "https://via.placeholder.com/150",
        },
      ],
    },
    {
      id: "4",
      title: "American",
      vendors: [
        {
          uid: "v2",
          name: "Burger Haven",
          price: "$$",
          rating: 4.0,
          latitude: 36.7398,
          longitude: -119.7891,
          image: "https://via.placeholder.com/150",
        },
        {
          uid: "v3",
          name: "Gourmet Grills",
          price: "$$$",
          rating: 3.8,
          latitude: 36.7358,
          longitude: -119.7851,
          image: "https://via.placeholder.com/150",
        },
        {
          uid: "v4",
          name: "Pizza Wagon",
          price: "$",
          rating: 4.7,
          latitude: 36.7388,
          longitude: -119.7861,
          image: "https://via.placeholder.com/150",
        },
        {
          uid: "v5",
          name: "Sandwich Stop",
          price: "$$",
          rating: 4.2,
          latitude: 36.7368,
          longitude: -119.7881,
          image: "https://via.placeholder.com/150",
        },
        {
          uid: "v15",
          name: "Fried Chicken Co.",
          price: "$$",
          rating: 4.5,
          latitude: 36.7498,
          longitude: -119.7991,
          image: "https://via.placeholder.com/150",
        },
      ],
    },
    {
      id: "5",
      title: "Japanese",
      vendors: [
        {
          uid: "v16",
          name: "Sushi Station",
          price: "$$$",
          rating: 4.8,
          latitude: 36.7508,
          longitude: -119.8001,
          image: "https://via.placeholder.com/150",
        },
        {
          uid: "v17",
          name: "Ramen Road",
          price: "$$",
          rating: 4.6,
          latitude: 36.7518,
          longitude: -119.8011,
          image: "https://via.placeholder.com/150",
        },
        {
          uid: "v18",
          name: "Tempura Truck",
          price: "$$",
          rating: 4.4,
          latitude: 36.7528,
          longitude: -119.8021,
          image: "https://via.placeholder.com/150",
        },
        {
          uid: "v19",
          name: "Teriyaki Treats",
          price: "$",
          rating: 4.3,
          latitude: 36.7538,
          longitude: -119.8031,
          image: "https://via.placeholder.com/150",
        },
        {
          uid: "v20",
          name: "Sashimi Stop",
          price: "$$$",
          rating: 4.7,
          latitude: 36.7548,
          longitude: -119.8041,
          image: "https://via.placeholder.com/150",
        },
      ],
    },
  ];